[project]
name = "hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zelia-x86", email = "209870153+zelia-x86@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
hw = "hw:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
